# type: ignore
"""company object

Revision ID: 1227c50194d8
Revises: b98b16007267
Create Date: 2020-08-09 16:50:56.371548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1227c50194d8"
down_revision = "b98b16007267"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column(
            "number_of_employees_estimate",
            sa.String(length=255),
            server_default="",
            nullable=True,
        ),
        sa.Column("name", sa.String(length=255), server_default="", nullable=False),
        sa.Column("address", sa.String(length=255), server_default="", nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "status", sa.String(length=255), server_default="active", nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.add_column("users", sa.Column("company_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_users_company_id_companies"),
        "users",
        "companies",
        ["company_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_company_id_companies"), "users", type_="foreignkey"
    )
    op.drop_column("users", "company_id")
    op.drop_table("companies")
    # ### end Alembic commands ###
