# type: ignore
"""add cancellation_period_weeks

Revision ID: 1bcca3244ba8
Revises: c8853b4393ca
Create Date: 2020-08-02 17:53:51.670461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1bcca3244ba8"
down_revision = "c8853b4393ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "isas", sa.Column("cancellation_period_weeks", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("isas", "cancellation_period_weeks")
    # ### end Alembic commands ###
