# type: ignore
"""feature flags

Revision ID: 51b6c81692f7
Revises: 6fa73044f08b
Create Date: 2020-09-02 17:25:12.450291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "51b6c81692f7"
down_revision = "6fa73044f08b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("name", sa.String(length=50), autoincrement=False, nullable=False),
        sa.Column("value", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_feature_flags")),
    )
    op.create_index(
        op.f("ix_feature_flags_name"), "feature_flags", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feature_flags_name"), table_name="feature_flags")
    op.drop_table("feature_flags")
    # ### end Alembic commands ###
