# type: ignore
"""expiration period in months for ISA

Revision ID: 6fa73044f08b
Revises: 2820835f411a
Create Date: 2020-08-31 15:28:26.212600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6fa73044f08b"
down_revision = "2820835f411a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "isas", sa.Column("expiration_period_months", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("isas", "expiration_period_months")
    # ### end Alembic commands ###
