# type: ignore
"""add company to PlaidItem object

Revision ID: 84404c87fbe7
Revises: 1227c50194d8
Create Date: 2020-08-11 13:04:12.406201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "84404c87fbe7"
down_revision = "1227c50194d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plaid_items", sa.Column("company_id", sa.Integer(), nullable=True))
    op.drop_constraint("uq_plaid_items_user_id", "plaid_items", type_="unique")
    op.create_unique_constraint(
        op.f("uq_plaid_items_user_id"),
        "plaid_items",
        ["user_id", "institution_id", "company_id"],
    )
    op.create_foreign_key(
        op.f("fk_plaid_items_company_id_companies"),
        "plaid_items",
        "companies",
        ["company_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_plaid_items_company_id_companies"), "plaid_items", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_plaid_items_user_id"), "plaid_items", type_="unique")
    op.create_unique_constraint(
        "uq_plaid_items_user_id", "plaid_items", ["user_id", "institution_id"]
    )
    op.drop_column("plaid_items", "company_id")
    # ### end Alembic commands ###
