# type: ignore
"""cancellation period in weeks

Revision ID: b98b16007267
Revises: 1bcca3244ba8
Create Date: 2020-08-09 16:49:33.279009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b98b16007267"
down_revision = "1bcca3244ba8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "isas", "cancellation_period_weeks", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "isas", "cancellation_period_weeks", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
