# type: ignore
"""coaches, students, and ISAs

Revision ID: c8853b4393ca
Revises: afb0dc244186
Create Date: 2020-07-16 14:56:05.560192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8853b4393ca"
down_revision = "afb0dc244186"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coaches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_coaches_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coaches")),
    )
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_students_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
    )
    op.create_table(
        "isas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("current_income", sa.Integer(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=False),
        sa.Column("cap", sa.Integer(), nullable=False),
        sa.Column("time_to_be_paid", sa.Integer(), nullable=False),
        sa.Column(
            "description", sa.String(length=255), server_default="", nullable=False
        ),
        sa.Column("status", sa.String(length=255), server_default="", nullable=False),
        sa.Column("coach_id", sa.Integer(), nullable=True),
        sa.Column("student_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["coaches.id"],
            name=op.f("fk_isas_coach_id_coaches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_isas_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_isas")),
    )
    op.add_column("users", sa.Column("type", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "type")
    op.drop_table("isas")
    op.drop_table("students")
    op.drop_table("coaches")
    # ### end Alembic commands ###
