# type: ignore
"""new fields to isa

Revision ID: e57929d9175c
Revises: 84404c87fbe7
Create Date: 2020-08-12 15:29:37.175569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e57929d9175c"
down_revision = "84404c87fbe7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "isas", sa.Column("industry_field", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "isas", sa.Column("program_duration_weeks", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("isas", "program_duration_weeks")
    op.drop_column("isas", "industry_field")
    # ### end Alembic commands ###
